# Generated by Django 5.0.6 on 2024-06-08 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0003_trip_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/uploaded'),
        ),
    ]
