# Generated by Django 5.0.6 on 2024-06-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0005_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='event',
            name='long',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
