# Generated by Django 5.0.6 on 2024-06-10 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0007_alter_event_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='people_count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
